<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "simpleblog-ext"
 *
 * Auto generated by Extension Builder 2021-08-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Simple Blog Extension Erweiterung',
    'description' => 'Demo extension to implement a simple Blog, based in the TYPO3 Extbase book',
    'category' => 'plugin',
    'author' => 'Autor Name',
    'author_email' => 'xxx@xx.de',
    'state' => 'alpha',
    'uploadfolder' => 1,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
